urls.py
from django.conf.urls import url

from . import views
from views import AccountCreateView, AccountUpdateView, QuoteCreateView, QuoteUpdateView, AccountSearchListView, ClassCodeSearch, APIView

app_name = 'djangoinsurancerater'
urlpatterns = [  
    url(r'^$', AccountCreateView.as_view(), name='account-create-view'),
    url(r'^codes/$', ClassCodeSearch.as_view(), name='class-code-search-view'),
    url(r'^api/$', APIView.as_view(), name='api-view'),
    url(r'^accounts/search/$', AccountSearchListView.as_view(), name='account-search-list-view'),
    url(r'^accounts/(?P<pk>\d+)/$', AccountUpdateView.as_view(), name='account-update-view'),
    url(r'^accounts/(?P<pk>\d+)/quote/$', QuoteCreateView.as_view(), name='quote-create-view'),
    url(r'^accounts/(?P<pk>\d+)/quote/(?P<quoteid>\d+)$', QuoteUpdateView.as_view(), name='quote-update-view')
]

templates/djangoinsurancerater/accountinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "djangoinsurancerater/bootstrapstyle.css" %} />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <title>{% block title %}{{accountinfoform.instance.name}}{% endblock %}</title>
</head>

<body>
  <div class="container">
    
    <div class="row header">
      
      <div class="col-md-12">      
        <h3 class="text-center">
        Update Your Account: {{accountinfoform.instance.name}}
        </h3>   
      </div>
      
    </div>
      
    
    <div class="row firstrow">
      
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"> 
        
        <div class="accountinfoform">
          {% include "djangoinsurancerater/accountinfoform.html" %}
            <a href="{% url 'djangoinsurancerater:quote-create-view' pk=accountinfoform.instance.id %}" class="btn btn-primary" id="newquotebutton">New Quote</a>
        </div>
        
      </div>
      
      <div class="row" id="quotesrow">
        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h2>
            Recent Quotes
          </h2>
          {% include "djangoinsurancerater/recentquotes.html" %}
        </div>
        
      </div>
      
    </div>
    
  </div>
</body>  
  
</html>

templates/djangoinsurancerater/accountinfo_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "djangoinsurancerater/bootstrapstyle.css" %} />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <title>{% block title %}Account Search Results{% endblock %}</title>
</head>
<body>
  <div class="container">
    
     <div class="row header">
       
       <div class="col-lg-12">
        <h3 class="text-center">
          Account Search Results
        </h3>
       </div>
       
     </div>
    
    <div class="row">
      
      <div class="col-lg-12">
        <table class="table-striped table-hover" id="searchresulttable">   
          <tr>
            <th>Account Name</th>
            <th>Date</th>
            <th>Underwriter</th>
          </tr>
          {% for account in object_list %}
          <tr>
            <td class="text-align-left"><a href="{% url 'djangoinsurancerater:account-update-view' pk=account.id %}">{{ account.name }}</a></td>
            <td>{{ account.date }}</td>
            <td>{{ account.underwriter}} </td>
          </tr>
          {% endfor %}
        </table>
     </div>
      
   </div>
    
  </div>    
</body>

templates/djangoinsurancerater/accountinfoform.html
{% block accountinfoform %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  {% csrf_token %}
  <div class="form-group">
    {{ accountinfoform.name.errors }}
    {{ accountinfoform.name.label_tag }}
    <input type="text" class="form-control"
           name="{{ accountinfoform.name.name }}"
           id="{{ accountinfoform.name.name }}"
           value="{{ accountinfoform.name.value }}"       >
    {% if accountinfoform.name.help_text %}
    <p class="help">
      {{ accountinfoform.name.help_text|safe }}
    </p>
    {% endif %}      
  </div>
  
  <div class="form-group">
    {{ accountinfoform.underwriter.errors }}
    {{ accountinfoform.underwriter.label_tag }}
    <input type="text" class="form-control"
           name="{{ accountinfoform.underwriter.name }}"
           id="{{ accountinfoform.underwriter.name }}"
           value="{{ accountinfoform.underwriter.value }}"       >
    {% if accountinfoform.underwriter.help_text %}
    <p class="help">
      {{ accountinfoform.underwriter.help_text|safe }}
    </p>
    {% endif %}     
  </div>
  
  <div class="form-group">
    {{ accountinfoform.rating_state.errors }}
    {{ accountinfoform.rating_state.label_tag }}
    {{ accountinfoform.rating_state }}
  </div>
  
  <div class="form-group">
    {{ accountinfoform.entity_type.errors }}
    {{ accountinfoform.entity_type.label_tag }}
    {{ accountinfoform.entity_type }}
  </div> 
{% endblock %}

templates/djangoinsurancerater/classcode_list.html
{% for classcode in object_list %}
<div class="row class-code-row">
  <div class="col-md-6 class-code-div">
    {{ classcode.class_code }}
  </div>
  <div class="col-md-6 class-description-div">
    {{ classcode.description }}
  </div>
</div>
{% endfor %}

templates/djangoinsurancerater/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "djangoinsurancerater/bootstrapstyle.css" %} />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <title>{% block title %}Crime Rater 2016{% endblock %}</title>
</head>

<body>
  <div class="container">
    
    <div class="row header">
      
      <div class="col-md-12">      
        <h3 class="text-center">
          Search for an Account or Create New
        </h3>
      </div>
      
    </div>
    
    <div class="row" id="firstrow">
      
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">        
      
        <div class="accountinfoform">
          <form action="" method="post" id=accountinfoform>
            {% include "djangoinsurancerater/accountinfoform.html" %}
          <button class="btn btn-primary" type="submit" form="accountinfoform">{% if accountinfoform.instance.id %} Update {% else %} Create {% endif %}</button>
          </form>
        </div>
      
      </div>
      
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <form id="searchform" action="{% url 'djangoinsurancerater:account-search-list-view' %}" method="get" accept-charset="utf-8">
              <div class="input-group">
                <span class="input-group-btn">
                  <button class="btn btn-primary" form="searchform" type="submit">Search</button>
                </span>
              <input class="form-control" id="searchbox" name="q" type="text" placeholder="Search">
              </div>
            </form>
      </div>
      
    </div>
      
      <div class="row" id="recentaccountsrow">
        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="recentaccounts">
          <h2>
            Recent Accounts
          </h2>          
            {% include "djangoinsurancerater/recentaccounts.html" %}   
        </div>
        
      </div>
      
  </div>
 
</body>  
  
</html>

templates/djangoinsurancerater/quote.html
{% load static %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "djangoinsurancerater/bootstrapstyle.css" %} />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src={% static "djangoinsurancerater/scripts.js" %}></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <title>{% block title %}{{accountinfoform.instance.name}}{% endblock %}</title>
</head>

<body>
 <div class="wrapper">
    
  <div class="container">
    
    <div class="row header">
      
      <div class="col-lg-12">        
        <h3>
          Quote Your Account: {{accountinfoform.instance.name}}
        </h3>
      </div>
      
    </div>
    
    
    <div class="row mediummarginbottom">
     <form action="" method="post" id="accountinfoform" class="accountinfoform">  
                 {% csrf_token %}
          <div class="col-md-6 col-lg-6">        
              {% include "djangoinsurancerater/accountinfoform.html" %}      
          </div>
      
          <div class="col-md-6 col-lg-6 riskdatagroup">
              {% csrf_token %}
            <div class="form-group">
                {{ riskdataform.employee_count.errors }}
                {{ riskdataform.employee_count.label_tag }}
                {{ riskdataform.employee_count }}
                {% if riskdataform.employee_count.help_text %}
                <p class="help">
                  {{ riskdataform.employee_count.help_text|safe }}
                </p>
                {% endif %}      
            </div>
            <div class="form-group">
                {{ riskdataform.rateable_count.errors }}
                {{ riskdataform.rateable_count.label_tag }}
                {{ riskdataform.rateable_count }}
                {% if riskdataform.rateable_count.help_text %}
                <p class="help">
                  {{ riskdataform.rateable_count.help_text|safe }}
                </p>
                {% endif %}      
            </div>
            <div class="form-group">
                {{ riskdataform.locations.errors }}
                {{ riskdataform.locations.label_tag }}
                {{ riskdataform.locations }}
                {% if riskdataform.locations.help_text %}
                <p class="help">
                  {{ riskdataform.locations.help_text|safe }}
                </p>
                {% endif %}      
            </div>
            <div class="form-group" id="classcodesection">
                {{ classcodeform.class_code.errors }}
                {{ classcodeform.class_code.label_tag }}
                <div class="input-group">
                {{ classcodeform.class_code }}
                  <span class="input-group-addon glyphicon glyphicon-search btn btn-primary" id="classcodesearchspan"></span>  
                </div>
                {% if classcodeform.class_code.help_text %}
                <p class="help">
                  {{ classcodeform.class_code.help_text|safe }}
                </p>
                {% endif %}      
            </div>
            <button type="submit" class="btn btn-primary" value="submit" form="accountinfoform">
              Update
            </button>  
              
      </div>
          
        
      </form> 
    </div>
    
      
    <div class="row hidden-sm hidden-xs mediummarginbottom">
      <div class="col-md-3">
        <h4>
          Agreement Type
        </h4>
        <h5>
          Set Global Value
        </h5>
      </div>
      <div class="col-md-3">
        <h4>
          Limit
        </h4>
        <input type=text placeholder="limit" id="global-limit">
      </div>
      <div class="col-md-3">
        <h4>
          Deductible
        </h4>
        <input type=text placeholder="deductible" id="global-deductible">
      </div>
      <div class="col-md-3">
        <h4>
          Premium
        </h4>
      </div>
    </div>
    
    <!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="alert" aria-labelledby="confirmModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Overwrite Current Values?</h4>
      </div>
      <div class="modal-body">
        Do you want to overwrite the current value for limits or deductibles and replace them with new global values?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        <button type="button" id="confirmYesButton" data-dismiss="modal" class="btn btn-primary">Yes</button>
      </div>
    </div>
  </div>
</div>
    
<!-- Modal -->
<div class="modal fade" id="classCodeSearchModal" tabindex="-1" role="alert" aria-labelledby="classCodeSearchModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="classCodeSearchModalLabel">Class Code Search</h4>
      </div>
      <div class="modal-body" id="classCodeSearchModalBody">
        
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>      
    

    {% for insuringagreementform in insuring_agreement_forms %}
    <div class="row insuringagreementrow text-justify">
      
      <form class = "insuring-agreement-form" action="" method="post">
        {% csrf_token %}
      <div class="col-md-3">               
          <div class="form-group">            
            <h5>
              <span class="glyphicon glyphicon-remove"></span> {{ insuringagreementform.instance.agreement_type }}:
            </h5>           
            {{ insuringagreementform.agreement_type }}
          </div>        
      </div>
      <div class="col-md-3">
        <div class="form-group limit">
          {{ insuringagreementform.insurance_limit }}
        </div>        
      </div>
      <div class="col-md-3">
        <div class="form-group deductible">
          {{ insuringagreementform.deductible }}
        </div>        
      </div>
      <div class="col-md-3">
        <div id=" {{ insuringagreementform.instance.agreement_type.id }}-premium" class="form-group premium">
          <p class="premium">
            ${{ insuringagreementform.instance.premium }}
          </p>
        </div>        
      </div>
        
     </form>   
    </div>
      
      {% endfor %}    
  </div>
   <div class="push"></div>
</div> 
 <div class="container">
       <footer class="footer"> 
        <h3 class="disclaimer text-center">
          This is a working demo and none of these premiums are "real"
        </h3>
      </footer>
 </div>
       

</body>

templates/djangoinsurancerater/quotes.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="post">
  {% csrf_token %}
  {{ accountinfoform.as_p }}
    {% if form.has_changed %} 
    <input type="submit" value="Update" />
    {% else %}
    <input type="submit" value="Submit" />
    {% endif %}
</form>

<form action="" method="post">
  {% csrf_token %}
  {{ riskdataform.as_p }}
    {% if form.has_changed %} 
    <input type="submit" value="Update" />
    {% else %}
    <input type="submit" value="Submit" />
    {% endif %}
</form>

templates/djangoinsurancerater/recentaccounts.html
{% block recentaccounts %}
  <div class="list-group">
   {% for account in lastfiveaccounts %}
    <a href="{% url 'djangoinsurancerater:account-update-view' pk=account.id %}" class="list-group-item">{{ account.name }}</a>
   {% empty %}
    <li class="list-group-item alert alert-danger" role="alert">There are no recent accounts.</li>
   {% endfor %}
  </ul>
{% endblock %}
 

templates/djangoinsurancerater/recentquotes.html
{% block recentquotes %}
  <div class="list-group">
   {% for quote in lastfivequotes %}
    <a href="{% url 'djangoinsurancerater:quote-update-view' pk=quote.account_info.id quoteid=quote.id %}" class="list-group-item">{{ quote.created_time }}</a>
   {% empty %}
    <li class="list-group-item alert alert-danger" role="alert">There are no recent quotes.</li>
   {% endfor %}
  </ul>
{% endblock %}
 